language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
sudo: false
branches:
  only:
    - master
    - travis-test
install:
  - pip install .
  - pip install -r requirements.txt
script: pytest
