language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
  - "pypy-5.3.1"
sudo: false
branches:
  only:
    - master
install:
  - pip install .
  - pip install -r requirements.txt
  - "pip install jinja2"
script: pytest
